// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlateformeFormation.Api.Data;

#nullable disable

namespace PlateformeFormation.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715105608_ValidationComptesUtilisateur")]
    partial class ValidationComptesUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PlateformeFormation.Api.Models.AlerteDoublon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDetection")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_detection");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("decision");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    b.Property<int>("DocumentSimilaireId")
                        .HasColumnType("int")
                        .HasColumnName("document_similaire_id");

                    b.Property<decimal?>("ScoreSimilarite")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("score_similarite");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentSimilaireId");

                    b.ToTable("alertes_doublons", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Domaine")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("domaine");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("libelle");

                    b.HasKey("Id");

                    b.ToTable("competences", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorieId")
                        .HasColumnType("int")
                        .HasColumnName("categorie_id");

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("chemin_fichier");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_ajout");

                    b.Property<string>("HashDocument")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hash_document");

                    b.Property<string>("Langue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("langue");

                    b.Property<int?>("NombrePages")
                        .HasColumnType("int")
                        .HasColumnName("nombre_pages");

                    b.Property<string>("OrigineCategorie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("origine_categorie");

                    b.Property<string>("Resume")
                        .HasColumnType("longtext")
                        .HasColumnName("resume");

                    b.Property<string>("StatutTraitement")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("statut_traitement");

                    b.Property<long?>("TailleFichier")
                        .HasColumnType("bigint")
                        .HasColumnName("taille_fichier");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titre");

                    b.Property<string>("TypeDocument")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type_document");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.DocumentCompetence", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int")
                        .HasColumnName("competence_id");

                    b.HasKey("DocumentId", "CompetenceId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("document_competences", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.DocumentSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenuTexte")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contenu_texte");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    b.Property<int>("Ordre")
                        .HasColumnType("int")
                        .HasColumnName("ordre");

                    b.Property<string>("VecteurId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vecteur_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("document_segments", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.ExportHistorique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("chemin_fichier");

                    b.Property<DateTime>("DateExport")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_export");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("format");

                    b.Property<int>("FormationId")
                        .HasColumnType("int")
                        .HasColumnName("formation_id");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("exports_historique", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activites")
                        .HasColumnType("longtext")
                        .HasColumnName("activites");

                    b.Property<int>("CreePar")
                        .HasColumnType("int")
                        .HasColumnName("cree_par");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<decimal?>("DureeEstimee")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("duree_estimee");

                    b.Property<string>("MethodesEvaluation")
                        .HasColumnType("longtext")
                        .HasColumnName("methodes_evaluation");

                    b.Property<string>("Modules")
                        .HasColumnType("longtext")
                        .HasColumnName("modules");

                    b.Property<string>("Objectifs")
                        .HasColumnType("longtext")
                        .HasColumnName("objectifs");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("statut");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titre");

                    b.HasKey("Id");

                    b.HasIndex("CreePar");

                    b.ToTable("formations", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.FormationDocument", b =>
                {
                    b.Property<int>("FormationId")
                        .HasColumnType("int")
                        .HasColumnName("formation_id");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    b.Property<decimal?>("ScorePertinence")
                        .HasColumnType("decimal(5,4)")
                        .HasColumnName("score_pertinence");

                    b.HasKey("FormationId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("formation_documents", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.JournalActivite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("action");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_action");

                    b.Property<string>("EntiteConcernee")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("entite_concernee");

                    b.Property<int?>("EntiteId")
                        .HasColumnType("int")
                        .HasColumnName("entite_id");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("journal_activite", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contenu");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_envoi");

                    b.Property<string>("Emetteur")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("emetteur");

                    b.Property<string>("SourcesDocuments")
                        .HasColumnType("longtext")
                        .HasColumnName("sources_documents");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("contenu");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<bool>("Lue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("lue");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int")
                        .HasColumnName("utilisateur_id");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("actif");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_creation");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_naissance");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_validation");

                    b.Property<string>("Departement")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("departement");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("derniere_connexion");

                    b.Property<string>("Discipline")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("discipline");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(190)
                        .HasColumnType("varchar(190)")
                        .HasColumnName("email");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mot_de_passe_hash");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nom");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("role");

                    b.Property<string>("StatutCompte")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("EN_ATTENTE")
                        .HasColumnName("statut_compte");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telephone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateurs", (string)null);
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.AlerteDoublon", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateformeFormation.Api.Models.Document", "DocumentSimilaire")
                        .WithMany()
                        .HasForeignKey("DocumentSimilaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("DocumentSimilaire");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Conversation", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("Conversations")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Document", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Categorie", "Categorie")
                        .WithMany("Documents")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlateformeFormation.Api.Models.Utilisateur", "Uploader")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.DocumentCompetence", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Competence", "Competence")
                        .WithMany("DocumentCompetences")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateformeFormation.Api.Models.Document", "Document")
                        .WithMany("DocumentCompetences")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.DocumentSegment", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Document", "Document")
                        .WithMany("Segments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.ExportHistorique", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Formation", "Formation")
                        .WithMany("Exports")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateformeFormation.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Formation", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Utilisateur", "Createur")
                        .WithMany("Formations")
                        .HasForeignKey("CreePar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.FormationDocument", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Document", "Document")
                        .WithMany("FormationDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlateformeFormation.Api.Models.Formation", "Formation")
                        .WithMany("FormationDocuments")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.JournalActivite", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("JournalActivites")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Message", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Notification", b =>
                {
                    b.HasOne("PlateformeFormation.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("Notifications")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Categorie", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Competence", b =>
                {
                    b.Navigation("DocumentCompetences");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Document", b =>
                {
                    b.Navigation("DocumentCompetences");

                    b.Navigation("FormationDocuments");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Formation", b =>
                {
                    b.Navigation("Exports");

                    b.Navigation("FormationDocuments");
                });

            modelBuilder.Entity("PlateformeFormation.Api.Models.Utilisateur", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Documents");

                    b.Navigation("Formations");

                    b.Navigation("JournalActivites");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
