services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: plateformeformation-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_BIND_ADDR: 0.0.0.0:1025
      MP_WEB_BIND_ADDR: 0.0.0.0:8025
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"
    restart: unless-stopped
