using System.IO;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Validation;
using PlateformeFormation.Api.Models;
using PlateformeFormation.Api.Services;

namespace PlateformeFormation.Api.Tests;

public class FormationPptxExportServiceTests
{
    private static Formation BuildFormation() => new()
    {
        Id = 1,
        Titre = "Formation DevOps",
        CreePar = 1,
        Objectifs = """
            {
              "sousTitre": "Intégration et livraison continues",
              "publicCible": "Développeurs",
              "prerequisDetailles": "Bases Git",
              "ressourcesPedagogiques": ["Documentation Docker"]
            }
            """,
        DureeEstimee = 6,
        Modules = """
            [
              {"numero":1,"titre":"Introduction à la culture DevOps","dureeHeures":3,"objectif":"Être capable de décrire les principes de base",
               "contenu":["Définition de la culture DevOps","Historique et évolution"],
               "methode":{"type":"Cours magistral","pctTheorie":80,"pctPratique":20},
               "livrable":"Schéma de la chaîne CI/CD",
               "exerciceFormatif":{"type":"TP","consigne":"Réaliser un schéma","dureeMin":30}},
              {"numero":2,"titre":"Intégration continue avec Jenkins","dureeHeures":3,"objectif":"Savoir configurer un serveur Jenkins",
               "contenu":["Présentation de Jenkins"],
               "livrable":"Rapport de configuration","reutiliseLivrableModule":1}
            ]
            """,
        Activites = "[]",
        MethodesEvaluation = """
            [
              {"nom":"Évaluation continue","pct":25,"estEvaluationContinue":true},
              {"nom":"Évaluation finale","pct":75,"estEvaluationContinue":false}
            ]
            """,
    };

    [Fact]
    public void GeneratePptx_ReturnsAWellFormedZipContainer()
    {
        var service = new FormationPptxExportService();
        var bytes = service.GeneratePptx(BuildFormation());

        Assert.NotEmpty(bytes);
        // .pptx is an OPC (ZIP) package — "PK\x03\x04" is the local-file-header magic number.
        Assert.Equal((byte)'P', bytes[0]);
        Assert.Equal((byte)'K', bytes[1]);
    }

    // Beyond "it's a ZIP" — reopen the generated bytes and run the OpenXml SDK's own schema
    // validator over every part. This is the strongest check available without PowerPoint installed:
    // a wrong element order or a missing required child would surface here as a validation error,
    // not just silently produce a file PowerPoint refuses to open.
    [Fact]
    public void GeneratePptx_ProducesSchemaValidPresentation()
    {
        var service = new FormationPptxExportService();
        var bytes = service.GeneratePptx(BuildFormation());

        using var stream = new MemoryStream(bytes);
        using var doc = PresentationDocument.Open(stream, false);

        var validator = new OpenXmlValidator();
        var errors = validator.Validate(doc).ToList();

        Assert.True(errors.Count == 0,
            string.Join("\n", errors.Select(e => $"{e.Path?.XPath}: {e.Description}")));

        var slideCount = doc.PresentationPart!.SlideParts.Count();
        // Title(1) + Sommaire(1, sections is non-empty) + Objectifs pédagogiques(1, both modules have
        // "objectif") + Agenda(1) + 2 modules + Évaluation(1) +
        // Ressources et pratique(1, ressourcesPedagogiques present) + Clôture(1, always present) = 9.
        // No Contexte/Bénéfices/Test de positionnement slides — none of that data is in this fixture.
        // No separate day-by-day Schedule slide — dropped from the deck entirely (not part of the
        // spec's slide outline; "Vue d'ensemble" is the module timeline only, exactly what Agenda
        // already is).
        Assert.Equal(9, slideCount);
    }

    [Fact]
    public void GeneratePptx_HandlesAFormationWithNoModules()
    {
        var formation = new Formation { Id = 2, Titre = "Vide", CreePar = 1, Objectifs = "{}", Modules = "[]", MethodesEvaluation = "[]" };
        var service = new FormationPptxExportService();

        var bytes = service.GeneratePptx(formation);

        using var stream = new MemoryStream(bytes);
        using var doc = PresentationDocument.Open(stream, false);
        // Title + Clôture — Clôture is unconditional (unlike the old "Ressources et sources" slide it
        // replaced, which silently vanished when there was nothing to list). No agenda/objectifs/
        // module/evaluation/ressources sections apply — there's no data for any of them.
        Assert.Equal(2, doc.PresentationPart!.SlideParts.Count());
    }

    // The reported bug: unmeasured free text overflowing its box and colliding with whatever came
    // next ("les lignes sont confondues"). Every long field here is realistic AI-generated-length
    // prose — the fix is that every block is measured and placed (or skipped) accordingly, which this
    // test can't visually confirm, but schema validity + no duplicate shape ids across the deck is a
    // solid proxy: an overflow bug that corrupted layout math previously also produced duplicate ids.
    [Fact]
    public void GeneratePptx_HandlesLongFreeTextWithoutSchemaErrorsOrDuplicateShapeIds()
    {
        var longSentence = "Ce module propose une exploration approfondie des pratiques professionnelles " +
            "les plus exigeantes du secteur, en combinant théorie solide, retours d'expérience concrets " +
            "et mises en situation réalistes pour ancrer durablement chaque compétence visée.";

        var formation = new Formation
        {
            Id = 3,
            Titre = "Une formation avec un titre particulièrement long qui devrait forcer une réduction automatique de la taille de police sur la diapositive de titre",
            CreePar = 1,
            Objectifs = """
                {
                  "sousTitre": "%LS%",
                  "publicCible": "%LS%",
                  "prerequisDetailles": "%LS%",
                  "ressourcesPedagogiques": ["%LS%", "%LS%"]
                }
                """.Replace("%LS%", longSentence),
            DureeEstimee = 7,
            Modules = """
                [
                  {"numero":1,"titre":"Un titre de module lui aussi anormalement long pour tester le rétrécissement",
                   "dureeHeures":7,"objectif":"%LS%",
                   "contenu":["%LS%","%LS%","%LS%","%LS%"],
                   "methode":{"type":"Atelier pratique intensif","pctTheorie":30,"pctPratique":70},
                   "livrable":"%LS%",
                   "exerciceFormatif":{"type":"Étude de cas","consigne":"%LS%","dureeMin":90}}
                ]
                """.Replace("%LS%", longSentence),
            Activites = "[]",
            MethodesEvaluation = """
                [
                  {"nom":"%LS%","pct":100,"estEvaluationContinue":true}
                ]
                """.Replace("%LS%", longSentence),
        };

        var service = new FormationPptxExportService();
        var bytes = service.GeneratePptx(formation);

        using var stream = new MemoryStream(bytes);
        using var doc = PresentationDocument.Open(stream, false);

        var errors = new OpenXmlValidator().Validate(doc).ToList();
        Assert.True(errors.Count == 0, string.Join("\n", errors.Select(e => $"{e.Path?.XPath}: {e.Description}")));

        AssertNoDuplicateShapeIds(doc);
    }

    // Enough modules to force both the Objectifs pédagogiques and Vue d'ensemble/sommaire slides to
    // paginate (5 rows/page) instead of fitting on one slide each.
    [Fact]
    public void GeneratePptx_ScalesAgendaAndScheduleForManyModules()
    {
        var modules = Enumerable.Range(1, 12).Select(i =>
            $"{{\"numero\":{i},\"titre\":\"Module numéro {i}\",\"dureeHeures\":2,\"objectif\":\"Objectif du module {i}\"}}");

        var formation = new Formation
        {
            Id = 4,
            Titre = "Formation avec de nombreux modules",
            CreePar = 1,
            Objectifs = "{}",
            DureeEstimee = 24,
            Modules = "[" + string.Join(",", modules) + "]",
            Activites = "[]",
            MethodesEvaluation = "[]",
        };

        var service = new FormationPptxExportService();
        var bytes = service.GeneratePptx(formation);

        using var stream = new MemoryStream(bytes);
        using var doc = PresentationDocument.Open(stream, false);

        var errors = new OpenXmlValidator().Validate(doc).ToList();
        Assert.True(errors.Count == 0, string.Join("\n", errors.Select(e => $"{e.Path?.XPath}: {e.Description}")));

        // Title(1) + Sommaire(1) + Objectifs pédagogiques (paginated: 12 modules / 5 per page = 3
        // pages) + Vue d'ensemble (paginated: 12 modules / 5 per page = 3 pages) + 12 module slides +
        // Clôture(1, always present) = 1 + 1 + 3 + 3 + 12 + 1 = 21. The exact page counts are what this
        // test exists to pin — if pagination math changes, this assertion should be revisited
        // deliberately.
        Assert.Equal(21, doc.PresentationPart!.SlideParts.Count());
        AssertNoDuplicateShapeIds(doc);
    }

    // A large module count (16) stress-tests pagination on every section that scales with it. The
    // real assertion is schema validity + no duplicate ids; visually confirming layout still requires
    // opening the file in PowerPoint.
    [Fact]
    public void GeneratePptx_HandlesManyScheduleDaysWithoutOverlap()
    {
        var modules = Enumerable.Range(1, 16).Select(i =>
            $"{{\"numero\":{i},\"titre\":\"Module {i} — sujet avancé\",\"dureeHeures\":7,\"objectif\":\"Objectif {i}\"}}");

        var formation = new Formation
        {
            Id = 5,
            Titre = "Formation longue avec seize jours de planning",
            CreePar = 1,
            Objectifs = "{}",
            DureeEstimee = 112,
            Modules = "[" + string.Join(",", modules) + "]",
            Activites = "[]",
            MethodesEvaluation = "[]",
        };

        var service = new FormationPptxExportService();
        var bytes = service.GeneratePptx(formation);

        using var stream = new MemoryStream(bytes);
        using var doc = PresentationDocument.Open(stream, false);

        var errors = new OpenXmlValidator().Validate(doc).ToList();
        Assert.True(errors.Count == 0, string.Join("\n", errors.Select(e => $"{e.Path?.XPath}: {e.Description}")));
        AssertNoDuplicateShapeIds(doc);

        // Objectifs pédagogiques paginates: 16 modules / 5 per page = 4 pages.
        // Vue d'ensemble also paginates: 16 modules / 5 per page = 4 pages.
        // Title(1) + Sommaire(1) + objectifs(4) + Vue d'ensemble(4) + 16 module slides + Clôture(1) = 27.
        Assert.Equal(27, doc.PresentationPart!.SlideParts.Count());
    }

    // The reported bug: the évaluation slide's loop `break`'d out the moment one item's real measured
    // height didn't fit the remaining space, silently dropping every item after it — 5 évaluation
    // entries in evaluation[] could render as only 3 bars with no indication 2 were missing. The fix
    // paginates onto additional slides instead, so every item must appear somewhere in the deck.
    [Fact]
    public void GeneratePptx_EvaluationSlidesRepresentEveryItemEvenWhenTheyDontFitOnOnePage()
    {
        var noms = new[]
        {
            "Évaluation continue – Suivi des exercices formatifs tout au long du parcours",
            "Évaluation finale – Projet de synthèse noté par un jury externe",
            "Quiz de mi-parcours sur les fondamentaux théoriques",
            "Projet final",
            "Participation et engagement",
        };
        var items = string.Join(",", noms.Select((n, i) =>
            $"{{\"nom\":\"{n}\",\"pct\":{(i + 1) * 15},\"estEvaluationContinue\":{(i % 2 == 0 ? "true" : "false")}}}"));

        var formation = new Formation
        {
            Id = 6,
            Titre = "Formation avec cinq modalités d'évaluation",
            CreePar = 1,
            Objectifs = "{}",
            Modules = "[]",
            Activites = "[]",
            MethodesEvaluation = "[" + items + "]",
        };

        var service = new FormationPptxExportService();
        var bytes = service.GeneratePptx(formation);

        using var stream = new MemoryStream(bytes);
        using var doc = PresentationDocument.Open(stream, false);

        var errors = new OpenXmlValidator().Validate(doc).ToList();
        Assert.True(errors.Count == 0, string.Join("\n", errors.Select(e => $"{e.Path?.XPath}: {e.Description}")));
        AssertNoDuplicateShapeIds(doc);

        var allText = doc.PresentationPart!.SlideParts
            .SelectMany(sp => sp.Slide!.Descendants<DocumentFormat.OpenXml.Drawing.Text>())
            .Select(t => t.Text)
            .ToList();

        foreach (var nom in noms)
        {
            // Truncate() may shorten a long name to fit its box — check a stable prefix rather than
            // the full string, which is exactly what would go missing if pagination regressed back to
            // a silent break.
            var prefix = nom.Length > 15 ? nom[..15] : nom;
            Assert.Contains(allText, t => t.StartsWith(prefix, StringComparison.Ordinal));
        }
    }

    // Regression for a real bug found in review: the Sommaire slide rendered every top-level section
    // on one fixed-height slide with no pagination and an unscaled 30pt numero glyph, unlike every
    // sibling list slide in this deck (Vue d'ensemble, Objectifs pédagogiques...) which paginates at 5
    // rows/page. A formation with every optional section present (Contexte, Objectifs, Bénéfices, Vue
    // d'ensemble, Modules, Test de positionnement, Évaluation, Ressources — 8 rows) used to cram all 8
    // onto one slide. This also verifies the Sommaire's own page count is correctly folded into the
    // slide numbers it prints for every later section — a formation this rich pushes the Sommaire
    // itself onto 2 pages, which shifts every subsequent slide number by one extra page.
    [Fact]
    public void GeneratePptx_SommaireWithEverySectionPresentPaginatesAndSlideNumbersStayAccurate()
    {
        var formation = new Formation
        {
            Id = 7,
            Titre = "Formation complète avec toutes les sections optionnelles",
            CreePar = 1,
            Objectifs = """
                {
                  "contexte": "Cette formation répond à un besoin identifié de montée en compétence sur les pratiques DevOps modernes",
                  "publicCible": "Développeurs",
                  "beneficesEntreprise": [{"titre": "Livraisons plus fréquentes", "justification": "Moins de régressions en production."}],
                  "ressourcesPedagogiques": ["Documentation officielle Jenkins"],
                  "testPositionnement": {"objectif": "Évaluer le niveau Git", "seuilParcoursStandardPct": 70}
                }
                """,
            DureeEstimee = 6,
            Modules = """
                [
                  {"numero":1,"titre":"Introduction à la culture DevOps","dureeHeures":3,"objectif":"Être capable de décrire les principes de base"},
                  {"numero":2,"titre":"Intégration continue avec Jenkins","dureeHeures":3,"objectif":"Savoir configurer un serveur Jenkins"}
                ]
                """,
            Activites = "[]",
            MethodesEvaluation = """[{"nom":"Évaluation continue","pct":100,"estEvaluationContinue":true}]""",
        };

        var service = new FormationPptxExportService();
        var bytes = service.GeneratePptx(formation);

        using var stream = new MemoryStream(bytes);
        using var doc = PresentationDocument.Open(stream, false);

        var errors = new OpenXmlValidator().Validate(doc).ToList();
        Assert.True(errors.Count == 0, string.Join("\n", errors.Select(e => $"{e.Path?.XPath}: {e.Description}")));
        AssertNoDuplicateShapeIds(doc);

        var slidesInOrder = GetSlidesInOrder(doc);

        // 8 sections / 5 per page = 2 Sommaire pages — title(1) + sommaire(2) precede everything else.
        var sommaireHeadingCount = slidesInOrder.Count(s => SlideHeadingText(s) == "Sommaire");
        Assert.Equal(2, sommaireHeadingCount);

        // For every section whose slide carries its own heading text (everything except the module
        // block, which uses a different per-module layout), the Sommaire's printed slide number must
        // match where that section's slide actually landed in the deck.
        var sectionHeadings = new[]
        {
            "Contexte et enjeux", "Objectifs pédagogiques", "Bénéfices pour l'entreprise",
            "Vue d'ensemble du programme", "Test de positionnement et différenciation",
            "Modalités d'évaluation", "Ressources et pratique",
        };
        var sommaireRows = slidesInOrder
            .Where(s => SlideHeadingText(s) == "Sommaire")
            .SelectMany(s => SommaireRows(s))
            .ToDictionary(r => r.Label, r => r.SlideNumber);

        foreach (var heading in sectionHeadings)
        {
            var actualSlideIndex = slidesInOrder.FindIndex(s => SlideHeadingText(s) == heading) + 1;
            Assert.True(actualSlideIndex > 0, $"No slide found with heading '{heading}'");
            Assert.True(sommaireRows.TryGetValue(heading, out var printedNumber), $"Sommaire has no row for '{heading}'");
            Assert.Equal(actualSlideIndex, printedNumber);
        }
    }

    // Returns slide parts in true document order (via SlideIdList's relationship ids) rather than
    // SlideParts' enumeration order, which isn't guaranteed to match insertion order.
    private static List<SlidePart> GetSlidesInOrder(PresentationDocument doc) =>
        doc.PresentationPart!.Presentation!.SlideIdList!.Elements<DocumentFormat.OpenXml.Presentation.SlideId>()
            .Select(id => (SlidePart)doc.PresentationPart!.GetPartById(id.RelationshipId!.Value!))
            .ToList()!;

    // AddPaperHeader/BuildTitleSlideV2 draw the section heading as a standalone text run — the first
    // text on the slide narrow enough to be a heading (module slides don't have one in this shape, by
    // design, since they use a different per-module layout).
    private static string? SlideHeadingText(SlidePart slidePart) =>
        slidePart.Slide!.Descendants<DocumentFormat.OpenXml.Presentation.Shape>()
            .FirstOrDefault(s => s.NonVisualShapeProperties?.NonVisualDrawingProperties?.Name?.Value == "heading")
            ?.TextBody?.Descendants<DocumentFormat.OpenXml.Drawing.Text>().FirstOrDefault()?.Text;

    // Reconstructs (label, printed slide number) rows from a Sommaire slide's own shapes — titreN and
    // pageN share the same row index N.
    private static IEnumerable<(string Label, int SlideNumber)> SommaireRows(SlidePart slidePart)
    {
        var shapes = slidePart.Slide!.Descendants<DocumentFormat.OpenXml.Presentation.Shape>().ToList();
        string? GetTextByName(string name) => shapes
            .FirstOrDefault(s => s.NonVisualShapeProperties?.NonVisualDrawingProperties?.Name?.Value == name)
            ?.TextBody?.Descendants<DocumentFormat.OpenXml.Drawing.Text>().FirstOrDefault()?.Text;

        for (var i = 0; ; i++)
        {
            var label = GetTextByName($"titre{i}");
            if (label is null) yield break;
            var pageText = GetTextByName($"page{i}");
            yield return (label, int.Parse(pageText ?? "0"));
        }
    }

    private static void AssertNoDuplicateShapeIds(PresentationDocument doc)
    {
        foreach (var slidePart in doc.PresentationPart!.SlideParts)
        {
            var ids = slidePart.Slide!.Descendants<DocumentFormat.OpenXml.Presentation.NonVisualDrawingProperties>()
                .Select(p => p.Id?.Value).ToList();
            var duplicates = ids.GroupBy(i => i).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
            Assert.True(duplicates.Count == 0, "Duplicate shape ids on a slide: " + string.Join(", ", duplicates));
        }
    }
}
